-- GENERATED by tools/build_seed.py from reviewed independent measurements.
-- Target client build: 70170. See the generation manifest and coverage report.
local _, ns = ...
ns.IndependentSeedData = {
}
ns.IndependentTransportData = {
}
