"""Regenerate Wayfinder/Data/Seed.lua from Carbonite's WoW: Forever guide data.

Wayfinder only *reveals* these locations once your exploration covers them (the same
moment the minimap would have shown the icon), so they behave like discoveries rather
than a pre-filled map. Recorded sightings always take priority over seed points.

Source: Carbonite All-in-One (GPL-3.0),
    https://github.com/IrcDirk/Carbonite-All-in-One-Retail-Classic
    Carbonite/Data/camelot/Guides/*.lua

Usage:
    python tools/build_seed.py <path-to-Carbonite-AIO-checkout>
"""

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "Wayfinder", "Data", "Seed.lua")

CLASSES = {
    "Druid": "DRUID", "Hunter": "HUNTER", "Mage": "MAGE", "Paladin": "PALADIN",
    "Priest": "PRIEST", "Rogue": "ROGUE", "Shaman": "SHAMAN", "Warlock": "WARLOCK",
    "Warrior": "WARRIOR",
}
PROFESSIONS = {
    "Alchemy", "Blacksmithing", "Cooking", "Enchanting", "Engineering", "FirstAid",
    "Fishing", "Herbalism", "Leatherworking", "Mining", "Riding", "Skinning", "Tailoring",
}
SIMPLE = {
    "Mailbox": ("mailbox", "Mailbox"),
    "Banker": ("bank", "Banker"),
    "Auctioneer": ("auction", "Auctioneer"),
    "Innkeeper": ("inn", "Innkeeper"),
}

POINT_TABLE_RE = re.compile(r'\[(\d+)\]\s*=\s*"([^"]*)"')
FLIGHT_RE = re.compile(r'\["(\d+),(\d+),([\d.]+),([\d.]+)"\]\s*=\s*L\["([^"]+)"\]')


def parse_points(text):
    points = []
    for map_id, blob in POINT_TABLE_RE.findall(text):
        for item in blob.split("|"):
            faction, x, y = item.split(",")
            points.append((int(map_id), float(x), float(y), int(faction)))
    return points


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    repo = sys.argv[1]
    guides = os.path.join(repo, "Carbonite", "Data", "camelot", "Guides")
    try:
        commit = subprocess.check_output(["git", "-C", repo, "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:
        commit = "unknown"

    entries = []  # (cat, label, classToken or None, points, names or None)
    for fname in sorted(os.listdir(guides)):
        stem, ext = os.path.splitext(fname)
        if ext != ".lua":
            continue
        text = open(os.path.join(guides, fname), encoding="utf-8-sig").read()
        if stem in SIMPLE:
            cat, label = SIMPLE[stem]
            entries.append((cat, label, None, parse_points(text), None))
        elif stem == "FlightMaster":
            points, names = [], []
            for faction, map_id, x, y, name in FLIGHT_RE.findall(text):
                points.append((int(map_id), float(x), float(y), int(faction)))
                names.append(name)
            entries.append(("flight", "Flight Master", None, points, names))
        elif stem.endswith("Trainer"):
            kind = stem[: -len("Trainer")]
            if kind in CLASSES:
                entries.append(("trainer_class", f"{kind} Trainer", CLASSES[kind], parse_points(text), None))
            elif kind in PROFESSIONS:
                label = "First Aid Trainer" if kind == "FirstAid" else f"{kind} Trainer"
                entries.append(("trainer_prof", label, None, parse_points(text), None))

    out = [
        "-- GENERATED by tools/build_seed.py. Do not edit by hand.",
        "-- Town service locations for WoW: Forever, derived from Carbonite All-in-One",
        f"-- (commit {commit}, Carbonite/Data/camelot/Guides), which is licensed GPL-3.0:",
        "-- https://github.com/IrcDirk/Carbonite-All-in-One-Retail-Classic",
        "-- Each pts list is flat: uiMapID, x%, y%, faction (0 neutral, 1 Alliance, 2 Horde).",
        "local _, ns = ...",
        "",
        "ns.SeedData = {",
    ]
    total = 0
    for cat, label, class_token, points, names in entries:
        total += len(points)
        head = f"\t{{ cat = {lua_string(cat)}, name = {lua_string(label)}"
        if class_token:
            head += f", class = {lua_string(class_token)}"
        out.append(head + ",")
        out.append("\t\tpts = {")
        for i in range(0, len(points), 6):
            chunk = points[i:i + 6]
            out.append("\t\t\t" + " ".join(f"{m},{x:g},{y:g},{f}," for m, x, y, f in chunk))
        out.append("\t\t},")
        if names:
            out.append("\t\tnames = {")
            for i in range(0, len(names), 4):
                out.append("\t\t\t" + " ".join(lua_string(n) + "," for n in names[i:i + 4]))
            out.append("\t\t},")
        out.append("\t},")
    out.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"{len(entries)} categories, {total} points -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
