"""Regenerate Wayfinder/Data/Tiles.lua from the client's own WDT files.

The minimap terrain tiles in WoW: Forever can only be loaded by FileDataID (their
CASC entries carry no name hash), so the addon ships a lookup table of
(continent, column, row) -> FileDataID. The authoritative source for that table is
each continent's WDT: its MAID chunk holds 64x64 entries of eight uint32 file IDs,
and slot 7 of each entry is the minimap texture.

Usage:
    python tools/build_tiles.py                 # uses the build below
    python tools/build_tiles.py 1.60.2.71234    # after a client patch

Files are fetched from wago.tools and cached in tools/.cache/.
"""

import os
import struct
import sys
import urllib.request

BUILD = "1.60.1.70170"

# instance (continent) ID -> (WDT FileDataID, label)
MAPS = {
    0: (775971, "Eastern Kingdoms (world/maps/azeroth)"),
    1: (782779, "Kalimdor (world/maps/kalimdor)"),
    2991: (7198644, "Zephras Isle (world/maps/2991)"),
    2997: (7251908, "Darkspear Islands (world/maps/2997)"),
}

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache")
OUT = os.path.join(HERE, "..", "Wayfinder", "Data", "Tiles.lua")


def fetch(fdid, build):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, f"{fdid}-{build}.wdt")
    if not os.path.exists(path):
        url = f"https://wago.tools/api/casc/{fdid}?version={build}"
        req = urllib.request.Request(url, headers={"User-Agent": "Wayfinder-build-tiles"})
        with urllib.request.urlopen(req, timeout=60) as resp, open(path, "wb") as fh:
            fh.write(resp.read())
    with open(path, "rb") as fh:
        return fh.read()


def chunks(data):
    pos = 0
    while pos + 8 <= len(data):
        magic = data[pos:pos + 4][::-1].decode("ascii", "replace")  # stored reversed
        size = struct.unpack_from("<I", data, pos + 4)[0]
        yield magic, data[pos + 8:pos + 8 + size]
        pos += 8 + size


def minimap_tiles(wdt):
    for magic, body in chunks(wdt):
        if magic == "MAID":
            entries = len(body) // 32
            if entries != 64 * 64:
                raise ValueError(f"unexpected MAID size: {entries} entries")
            tiles = {}
            for index in range(entries):
                minimap = struct.unpack_from("<8I", body, index * 32)[7]
                if minimap:
                    row, col = divmod(index, 64)  # MAID index = row * 64 + col
                    tiles[(col, row)] = minimap
            return tiles
    raise ValueError("WDT has no MAID chunk")


def main():
    build = sys.argv[1] if len(sys.argv) > 1 else BUILD
    lines = [
        "-- GENERATED by tools/build_tiles.py from the client's WDT files. Do not edit by hand.",
        f"-- Client build: {build}",
        "-- Keys are column * 100 + row of the 533.33-yard ADT grid; values are minimap",
        "-- texture FileDataIDs (512x512 in Forever).",
        "local _, ns = ...",
        "",
        f'ns.TileDataBuild = "{build}"',
        "ns.TileData = {",
    ]
    for cont, (fdid, label) in MAPS.items():
        tiles = minimap_tiles(fetch(fdid, build))
        print(f"{label}: {len(tiles)} tiles")
        lines.append(f"\t[{cont}] = {{ -- {label}, {len(tiles)} tiles")
        row_items = []
        for (col, row), file_id in sorted(tiles.items()):
            row_items.append(f"[{col * 100 + row}]={file_id}")
            if len(row_items) == 8:
                lines.append("\t\t" + ",".join(row_items) + ",")
                row_items = []
        if row_items:
            lines.append("\t\t" + ",".join(row_items) + ",")
        lines.append("\t},")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
